<Project>
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<DebugType>embedded</DebugType>
		<PackageId>$(MSBuildProjectName)</PackageId>
		<Company>BDCF, LLC</Company>
		<Authors>Brian DeMarzo</Authors>
		<Product>BDCF Extensions</Product>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
