<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>Entity Framework Core 10 conventions for relational defaults, enum check constraints, and enum value validation.</Description>
		<PackageTags>bdcf;extensions;entityframeworkcore;efcore;defaultvalue;enum;validation;conventions</PackageTags>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="C:\git\bdcf\bdcf-extensions\CHANGELOG.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_DACPAC.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_DATA.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_WEB.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\README.md" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
	</ItemGroup>

</Project>
