<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="C:\git\bdcf\bdcf-extensions\CHANGELOG.md" />
    <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS.md" />
    <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_DACPAC.md" />
    <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_DATA.md" />
    <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_WEB.md" />
    <None Remove="C:\git\bdcf\bdcf-extensions\README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Bdcf.Extensions.Data\Bdcf.Extensions.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
