<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Bdcf.Extensions.Web</PackageId>
		<Company>BDCF, LLC</Company>
		<Authors>Brian DeMarzo</Authors>
		<Product>BDCF Extensions</Product>
	</PropertyGroup>

	<PropertyGroup>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bdcf.Extensions\Bdcf.Extensions.csproj" />
	</ItemGroup>

</Project>
