<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Description>General-purpose .NET extension methods and validation helpers for strings, enums, objects, claims, types, booleans, decimals, and time spans.</Description>
		<PackageTags>bdcf;extensions;dotnet;helpers;data-annotations;claims</PackageTags>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="C:\git\bdcf\bdcf-extensions\CHANGELOG.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_DACPAC.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_DATA.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\docs\BDCF_EXTENSIONS_WEB.md" />
	  <None Remove="C:\git\bdcf\bdcf-extensions\README.md" />
	</ItemGroup>
</Project>
